### ISSUE TITLE
Versions autoupdate

### ISSUE THREAD

**Issue by rbukovansky** [kylef/swiftenv-api#11]
Could you please make that autoupdating, so we don't run into this https://github.com/kylef/swiftenv/issues/72 and you don't need to manually update the file?

I would like to have cronjob run once a day to check if it's able to install latest snapshot on my DEV machine.

Thank you.

**Comment by tkrajacic** [comment]
Especially since the release plan for Swift 3.1 suggests that there will be daily snapshots 😉

**Comment by rbukovansky** [comment]
Better yet, why `swiftenv` by itself doesn't check the availability of given package on `swift.org`?

**Comment by kylef** [comment]
> Better yet, why `swiftenv` by itself doesn't check the availability of given package on `swift.org`?

The URL format for binaries has not been stable in the past, the format changed multiple times. There are many rules and it's complicated to guess the URL for a snapshot and test it. Swiftenv used to attempt this approach became unmanageable so I switched to an API which contained a full index to remove the complexity from the client. It's also difficult to remember all of these formats and test them all (dev builds from month X and year Y have format Z etc).

Before, every time the format changed, a new version of swiftenv would need to be created and existing versions of swiftenv are broken for newer Swift versions. I wanted to provide a more stable tool and the API mitigates these changes from swiftenv.

Swiftenv later started to contain a cache of the latest stable releases so hitting the API is not required (https://github.com/kylef/swiftenv/tree/master/share/swiftenv-install), but will fallback to the API containing full index. This allows the majority installs (against stable Swift versions) to pass

---

Auto updating is certainly something I've wanted to add, but it's been pretty lower priority compared to some of the other features/libraries I'm working on so hasn't been added so far. I have a few ideas on how I want to solve this so I'll make a PR soon adding this functionality.

**Comment by rbukovansky** [comment]
I see... Thanks, @kylef. It was just an idea... Had no clue you already went that rabbit hole... 😉

**Comment by kylef** [comment]
I'll keep this card open to track adding automatic version updating to the API.

**Comment by kylef** [comment]
https://github.com/kylef/swiftenv-api/commit/a35bb7fd01c295ca9db7843ab7311c6c4fb03d9b can handle commiting/syncing to GitHub. Just need to set up a cronjob to run this often and we should be good to go.

**Comment by rbukovansky** [comment]
:fireworks: :champagne: :wink:

**Comment by rbukovansky** [comment]
@kylef If DEV SNAPSHOTS 2017-03-19 were submitted automatically, then the autoupdate is  working. Could you please confirm? Thanks.

**Comment by kylef** [comment]
@rbukovansky I manually invoked the script. I will try manually invoking it every day until I get round to setting up automation. I'm travelling at the moment but when I get back I'll setup the automation.

**Comment by rbukovansky** [comment]
@kylef So, where are we with automation, please? Thanks.

**Comment by kylef** [comment]
https://github.com/kylef/swiftenv-api/issues/11#issuecomment-288025543

**Comment by kylef** [comment]
I set this up on a cron job about a month ago and it seems to be working reliably 🎉.

**Comment by rbukovansky** [comment]
That's true! Thank you!
