### ISSUE TITLE
API is down!

### ISSUE THREAD

**Issue by paulofaria** [kylef/swiftenv-api#9]
Looks like the API is down. We're getting 503.

https://circleci.com/gh/Zewo/Zewo/96

**Comment by paulofaria** [comment]
Heroku seems to be fine.

https://status.heroku.com

**Comment by kylef** [comment]
Unfortunately woken up to this email from the provider (Heroku):

> You have used all of your 2950 Free Dyno hours for September 2016.
>
> After August 1st, 2016, if you exceed your quota, all of your free dynos will sleep until the beginning of the following month.

I've paid them more monies and this should be working now.
